theme: jekyll-theme-cayman
show_downloads: true

github:
  zip_url: https://play.google.com/store/apps/details?id=devesh.ephrine.qr.code&referrer=utm_source%3Dwebsite%26utm_medium%3DTxWebsite%26utm_campaign%3Dapp%2Bdownload
  tar_url: https://github.com/DeveshRx/QR-Lite/releases/latest/download/app-release.apk
  is_project_page: true
#  url: https://textmaster.ephrine.in